### ISSUE TITLE
SEHException

### ISSUE THREAD

**Issue by SSDiver2112** [paulyoder/LinqToExcel#164]
I am getting this error System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.' When accessing xlsx files. No changes to the code, it just stopped working. 
            var excel = new ExcelQueryFactory(FullFileName);
            List<string> wsNames = excel.GetWorksheetNames().ToList();
This works for xls files but not xlsx files.

Thank You,
Scott

**Comment by mrworkman** [comment]
Can you tell me the following:
* Which version of LinqToExcel?
* Which version of the ACE driver are you using (if applicable), including whether it is 32 or 64 bit.
* Please include the full stack-trace, so I can see where the error occurred.
* Also, attach an xlsx file that you are seeing this problem with (I need to rule it out as a cause). You can create a new xlsx file, as long as it still reproduces the problem.

Thanks

**Comment by mrworkman** [comment]
Duplicates #163.

**Comment by SSDiver2112** [comment]
I Attached an Excel example, but it happens to all xlsx files.
Thank you,
Scott Snyder

LinqToExcel
    Assembly Version: 1.11.0.0
    Win32 Version: 1.11.0

32 bit ACE

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.SEHException (0x80004005): External
component has thrown an exception.
   at
System.Data.OleDb.DataSourceWrapper.InitializeAndCreateSession(OleDbConnectionString
constr, SessionWrapper& sessionWrapper)
   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString
constr, OleDbConnection connection)
   at
System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions
options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo,
DbConnectionPool pool, DbConnection owningObject)
   at
System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions
options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo,
DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions
userOptions)
   at
System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection
owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions
userOptions)
   at
System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection
owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions
userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&
connection)
   at
System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection
outerConnection, DbConnectionFactory connectionFactory,
TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at
System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection
outerConnection, DbConnectionFactory connectionFactory,
TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at
System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection
outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at LinqToExcel.Query.ExcelUtilities.GetWorksheetNames(ExcelQueryArgs
args)
   at LinqToExcel.Query.ExcelUtilities.GetWorksheetNames(String fileName,
ExcelQueryArgs args)
   at LinqToExcel.ExcelQueryFactory.GetWorksheetNames()
   at PPL_DataManagement.frmBulkLoader.gDFV_BulkLoad_FileSelected(String
FullFileName, String FileName) in
C:\Users\Scott\Source\Repos\PPL_DataManagement\PPL_DataManagement\FormViews\frmBulkLoader.cs:line
124
   at gControlLib.gDirFileView.FileView1_FileSelected(String FullFileName,
String FileName)
   at gControlLib.FileView.ListView1_SelectedIndexChanged(Object sender,
EventArgs e)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)

System.Runtime.InteropServices.SEHException
  HResult=0x80004005
  Message=External component has thrown an exception.
  Source=System.Data
  StackTrace:
   at
System.Data.OleDb.DataSourceWrapper.InitializeAndCreateSession(OleDbConnectionString
constr, SessionWrapper& sessionWrapper)
   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString
constr, OleDbConnection connection)
   at
System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions
options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo,
DbConnectionPool pool, DbConnection owningObject)
   at
System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions
options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo,
DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions
userOptions)
   at
System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection
owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions
userOptions)
   at
System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection
owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions
userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&
connection)
   at
System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection
outerConnection, DbConnectionFactory connectionFactory,
TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at
System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection
outerConnection, DbConnectionFactory connectionFactory,
TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at
System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection
outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at LinqToExcel.Query.ExcelUtilities.GetWorksheetNames(ExcelQueryArgs
args)
   at LinqToExcel.Query.ExcelUtilities.GetWorksheetNames(String fileName,
ExcelQueryArgs args)
   at LinqToExcel.ExcelQueryFactory.GetWorksheetNames()
   at PPL_DataManagement.frmBulkLoader.gDFV_BulkLoad_FileSelected(String
FullFileName, String FileName) in
C:\Users\Scott\Source\Repos\PPL_DataManagement\PPL_DataManagement\FormViews\frmBulkLoader.cs:line
125
   at gControlLib.gDirFileView.FileView1_FileSelected(String FullFileName,
String FileName)
   at gControlLib.FileView.ListView1_SelectedIndexChanged(Object sender,
EventArgs e)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd,
Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd,
Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.Control.SendMessage(Int32 msg, IntPtr wparam,
IntPtr lparam)
   at System.Windows.Forms.Control.ReflectMessageInternal(IntPtr hWnd,
Message& m)
   at System.Windows.Forms.Control.WmNotify(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd,
Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr
wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Control.DefWndProc(Message& m)
   at System.Windows.Forms.ListView.WmMouseDown(Message& m, MouseButtons
button, Int32 clicks)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd,
Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at
System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr
dwComponentID, Int32 reason, Int32 pvLoopData)
   at
System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32
reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32
reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at PPL_DataManagement.FormViews.frmStartUp.glblBulkLoader_Click(Object
sender, EventArgs e) in
C:\Users\Scott\Source\Repos\PPL_DataManagement\PPL_DataManagement\FormViews\frmStartUp.cs:line
377
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at gControlLib.gLabel.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons
button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd,
Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at
System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr
dwComponentID, Int32 reason, Int32 pvLoopData)
   at
System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32
reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32
reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at PPL_DataManagement.Dialogs.dlgLogin.ShowMain() in
C:\Users\Scott\Source\Repos\PPL_DataManagement\PPL_DataManagement\Dialogs\dlgLogin.cs:line
139
   at PPL_DataManagement.Dialogs.dlgLogin.OK_Click(Object sender, EventArgs
e) in
C:\Users\Scott\Source\Repos\PPL_DataManagement\PPL_DataManagement\Dialogs\dlgLogin.cs:line
169
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons
button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd,
Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at
System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr
dwComponentID, Int32 reason, Int32 pvLoopData)
   at
System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32
reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32
reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at PPL_DataManagement.Program.Main() in
C:\Users\Scott\Source\Repos\PPL_DataManagement\PPL_DataManagement\Program.cs:line
22

**Comment by mrworkman** [comment]
@SSDiver2112, github is lame and doesn't allow attachments on issues, apparently. Can you send a link to the file on OneDrive/DropBox/Google Drive ?

**Comment by SSDiver2112** [comment]
Here is a link to the file. It is just a new file i made for this example.
I can't get any xlsx to work anymore.
Thanks,
Scott

https://1drv.ms/x/s!AnQ6Hkbv2zwFhrE2mPDRlHTRIMFYQQ

**Comment by mrworkman** [comment]
Thanks. I should be able to check it out this weekend, but I notice you're using a v1 version of LinqToExcel. There's a v2 in pre-release (on nuget) that you could try in the meantime.

**Comment by SSDiver2112** [comment]
Thanks Stephen,
I tried v2 but then it did not like either xls or xlsx files (see below) so
I reverted back to v1.11.0 so I can at least convert and open the xls files
for now.

Thank you,
Scott Snyder

System.Runtime.InteropServices.SEHException
  HResult=0x80004005
  Message=External component has thrown an exception.
  Source=System.Data
  StackTrace:
   at
System.Data.OleDb.DataSourceWrapper.InitializeAndCreateSession(OleDbConnectionString
constr, SessionWrapper& sessionWrapper)
   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString
constr, OleDbConnection connection)
   at
System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions
options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo,
DbConnectionPool pool, DbConnection owningObject)
   at
System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions
options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo,
DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions
userOptions)
   at
System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection
owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions
userOptions)
   at
System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection
owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions
userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&
connection)
   at
System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection
outerConnection, DbConnectionFactory connectionFactory,
TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at
System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection
outerConnection, DbConnectionFactory connectionFactory,
TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at
System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection
outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at LinqToExcel.Query.ExcelUtilities.GetWorksheetNames(ExcelQueryArgs
args) in
E:\Opt\Projects\LinqToExcel\src\LinqToExcel\Query\ExcelUtilities.cs:line 92
   at LinqToExcel.Query.ExcelUtilities.GetWorksheetNames(String fileName,
ExcelQueryArgs origArgs) in
E:\Opt\Projects\LinqToExcel\src\LinqToExcel\Query\ExcelUtilities.cs:line 68
   at LinqToExcel.ExcelQueryFactory.GetWorksheetNames() in
E:\Opt\Projects\LinqToExcel\src\LinqToExcel\ExcelQueryFactory.cs:line 164
   at PPL_DataManagement.frmBulkLoader.gDFV_BulkLoad_FileSelected(String
FullFileName, String FileName) in
C:\Users\Scott\Source\Repos\PPL_DataManagement\PPL_DataManagement\FormViews\frmBulkLoader.cs:line
125
   at gControlLib.gDirFileView.FileView1_FileSelected(String FullFileName,
String FileName)
   at gControlLib.FileView.ListView1_SelectedIndexChanged(Object sender,
EventArgs e)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd,
Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd,
Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.Control.SendMessage(Int32 msg, IntPtr wparam,
IntPtr lparam)
   at System.Windows.Forms.Control.ReflectMessageInternal(IntPtr hWnd,
Message& m)
   at System.Windows.Forms.Control.WmNotify(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd,
Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr
wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Control.DefWndProc(Message& m)
   at System.Windows.Forms.ListView.WmMouseDown(Message& m, MouseButtons
button, Int32 clicks)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd,
Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at
System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr
dwComponentID, Int32 reason, Int32 pvLoopData)
   at
System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32
reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32
reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at PPL_DataManagement.FormViews.frmStartUp.LoadBulkLoader() in
C:\Users\Scott\Source\Repos\PPL_DataManagement\PPL_DataManagement\FormViews\frmStartUp.cs:line
904
   at PPL_DataManagement.FormViews.frmStartUp.glblBulkLoader_Click(Object
sender, EventArgs e) in
C:\Users\Scott\Source\Repos\PPL_DataManagement\PPL_DataManagement\FormViews\frmStartUp.cs:line
486
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at gControlLib.gLabel.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons
button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at gControlLib.gLabel.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd,
Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at
System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr
dwComponentID, Int32 reason, Int32 pvLoopData)
   at
System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32
reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32
reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at PPL_DataManagement.Dialogs.dlgLogin.ShowMain() in
C:\Users\Scott\Source\Repos\PPL_DataManagement\PPL_DataManagement\Dialogs\dlgLogin.cs:line
153
   at PPL_DataManagement.Dialogs.dlgLogin.dlgLogin_Shown(Object sender,
EventArgs e) in
C:\Users\Scott\Source\Repos\PPL_DataManagement\PPL_DataManagement\Dialogs\dlgLogin.cs:line
121
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at
System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry
tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)
   at
System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd,
Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at
System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr
dwComponentID, Int32 reason, Int32 pvLoopData)
   at
System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32
reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32
reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at PPL_DataManagement.Program.Main() in
C:\Users\Scott\Source\Repos\PPL_DataManagement\PPL_DataManagement\Program.cs:line
22

**Comment by mrworkman** [comment]
Hi @SSDiver2112,

Unfortunately, I'm not able to reproduce the problem. Looking up `OleDb SEHException 0x80004005`, I see a number of possible causes most notably:

- Platform bitness (x64 project & x32 ACE, or vice versa). I doubt this is your problem, usually you'd get an ACE exception instead.
- [Some kind of endpoint protection software](https://forums.asp.net/t/1704958.aspx?Re+SEHException+thrown+when+I+run+the+application). Are you experiencing this issue on a work PC?

Aside from that, it's difficult to tell with the error that was thrown. `0x80004005` is just `E_FAIL`, which could mean anything. But such a generic error _could_ indicate that something else is killing your DB connection (like endpoint protection / av) -- this would jive with the fact that you didn't make any code changes that could have lead to the failure.

I assume you've already done the re-install of the ACE driver, and other basic troubleshooting.
